config/routes.rb
Rails.application.routes.draw do


	resources :user_groups

	namespace :security_files do
		resources :sec_tags
		resources :sec_group_templates
		resources :flows
	end

	namespace :protocol_files do
		resources :nsx_managers
	end

	namespace :admin_files do
		resources :settings
		resources :vrni_applications
	end

	namespace :user_files do
	  resources :users
	end

	namespace :fire_wall_files do
		resources :temp_fire_rules
		resources :rule_histories
		resources :rule_templates
		resources :fire_rules
		resources :sug_rule
	end

	namespace :security_files do
		resources :sec_groups
	end
	
	resources :services
	resources :applied_tos
	resources :nested_sec_gps
	resources :app_objs
	resources :vms

	root 'user_files/users#home'

	resources :app do

		namespace :fire_wall_files do
			resources :temp_fire_rules do
				resources :port_ranges
				resources :protocols
				resources :applied_tos
				resources :destinations
				resources :sources
				resources :services
			end
		end

		collection { post :import } # import function's routes for the app csv file
	    resources :tiers do

	    	namespace :fire_wall_files do
		    	resources :sug_rules do
		    		resources :port_ranges
		    		resources :protocols
		    		resources :applied_tos
		    		resources :destinations
		    		resources :sources
		    		resources :services
		    	end
		    end

	    	resources :app_objs do
	    		namespace :fire_wall_files do
			  		resources :fire_rules do
						resources :port_ranges
						resources :protocols
						resources :applied_tos
						resources :destinations
						resources :sources
						resources :services
					end
				end
			end
		end
	end

	resources :sec_groups do
		collection {post :import_groups_and_objs} # import function's routes for the app csv file

		namespace :fire_wall_files do
			resources :sug_rules do
				collection { patch :add_sug_rules }
				resources :port_ranges
				resources :protocols
				resources :applied_tos
				resources :destinations
				resources :sources
				resources :services
			end
		end
		
		resources :nested_sec_gps do
			resources :app_objs
		end		
	end

	namespace :fire_wall_files do
		resources :fire_rules do
			collection { get :import_fw_rules }
			resources :port_ranges
			resources :protocols
			resources :applied_tos
			resources :destinations
			resources :sources
			resources :services
		end
	end
	
	namespace :fire_wall_files do
		resources :temp_fire_rules do

			resources :port_ranges
			resources :protocols
			resources :applied_tos
			resources :destinations
			resources :sources
			resources :services

		end
	end

	resources :sec_groups do
		namespace :fire_wall_files do
			resources :temp_fire_rules do

				resources :port_ranges
				resources :protocols
				resources :applied_tos
				resources :destinations
				resources :sources
				resources :services

			end
		end
	end


	resources :sec_groups do
		resources :flows
	end

	resources :nested_sec_gps do
		resources :flows
	end


###########################
#   Custom Routes Below
###########################


#   Flows 
	get '/allow_flow/:id', to: 'security_files/flows#allow_flow', as: "allow_flow"
	get '/deny_flow/:id', to: 'security_files/flows#deny_flow', as: "deny_flow"
	delete '/remove_flow/:id', to: 'security_files/flows#remove_flow_from_nsx', as: "remove_flow_from_nsx"

#   Application
	post '/filter/:column_array/object/:object_class', to: 'application#filter_columns', as: "filter_columns"
	get '/columns/select', to: 'application#select_filter_columns', as: "select_filter_columns"
	get '/filter/:row_totals/columns/:column_array/:origin', to: 'application#add_column_sort_modal_item', as: "add_column_sort_modal_item"

# 	Histories
	get '/remove_rule/:rule_id', to: "fire_wall_files/rule_histories#remove_nsx_rule", as: "remove_nsx_rule"
	get '/resubmit_rule/:rule_id', to: "fire_wall_files/rule_histories#resubmit_nsx_rule", as: "resubmit_nsx_rule"

#   rule_table
	get '/change_name', to: "application#add_to_table_column"

#   Rule Creation
	get '/sysobj/:template_id', to: "application#add_to_table_column", as: "add_protocol_by_num_to_table"
	get '/sgp_task/:task_id/:user_id', to: 'user_files/users#attach_sec_group_user', as: "attach_sec_group_user"
	get '/new_template_rule/:template_id/:rule_id', to: 'fire_wall_files/rule_templates#add_rules_to_template', as: "add_rules_to_template"
	post '/new_rule/:type/:which_action/:template_id/:rule_id/:which_controller/:vmware_object_id', to: 'application#add_to_table_column', as: "add_to_table_column"
	get '/delete_item/:template_id/:rule_id/:item_type/:item_id/:which_controller', to: "application#delete_rule_item", as: "delete_template_rule_item"

#   Templates
    post '/template/:id/name', to: 'fire_wall_files/rule_templates#set_template_name', as: "set_template_name"
	get '/new_template/', to: 'fire_wall_files/rule_templates#create_a_template', as: "create_a_template"
	get '/template/:id/new_rule/:rule_id', to: 'fire_wall_files/rule_templates#cancel_rule_to_template', as: "cancel_rule_to_template"
	get '/template/:id/rules', to: 'fire_wall_files/rule_templates#see_template_rules', as: "see_template_rules_lite"
	get '/template/:id/rules/:rule', to: 'fire_wall_files/rule_templates#see_template_rules', as: "see_template_rules"
	get '/template/:id', to: 'fire_wall_files/rule_templates#edit_template', as: "edit_template"
	delete '/template/:id', to: 'fire_wall_files/rule_templates#destroy', as: "delete_a_template"
	delete 'template/:template_id/rule/:rule_id', to: 'fire_wall_files/rule_templates#delete_a_template_rule', as: "delete_a_template_rule"
	get 'template/:template_id/rule/:rule_id', to: 'fire_wall_files/rule_templates#edit_a_template_rule', as: "edit_a_template_rule"
	# get 'search_templates', to: "fire_wall_files/rule_templates#search_templates"
	post 'template/:template_id', to: "fire_wall_files/rule_templates#add_template_to_group", as: "add_template_to_group"
	get '/search_templates', to: "fire_wall_files/rule_templates#search_templates", as: "search_templates"
	delete '/remove_template/:template_id', to: "fire_wall_files/rule_templates#remove_template_from_group", as: "remove_template_from_group"

#   User Setting
	get '/settings', to: 'admin_files/settings#index', as: "settings_index"
	patch '/edit_manager/:nsx', to: 'admin_files/settings#update_nsx', as: "nsx_manager_edit"
	patch '/edit_manager/:vrni', to: 'admin_files/settings#update_vrni', as: "vrin_machine_edit"
	post '/settings_error', to: 'admin_files/settings#settings_error', as: "settings_error"
	post '/settings_save', to: 'admin_files/settings#settings_save', as: "settings_save"
	post '/settings_cancel', to: 'admin_files/settings#settings_cancel', as: "settings_cancel"
	patch '/settings_update/:id/:type', to: 'admin_files/settings#settings_update', as: "settings_update"

#   Children of Settings Class
	post '/vrni_applications', to: 'admin_files/vrni_applications#create', as: "add_vrni"
	post '/nsx_managers', to: 'protocol_files/nsx_managers#create', as: "add_nsx"
	put '/edit_vrni/:id', to: 'admin_files/vrni_applications#destroy', as: "edit_vrni"
	put '/edit_nsx/:id', to: 'protocol_files/nsx_managers#destroy', as: "edit_nsx"
	delete '/delete_vrni/:id', to: 'admin_files/vrni_applications#destroy', as: "delete_vrni"
	delete '/delete_nsx/:id', to: 'protocol_files/nsx_managers#destroy', as: "delete_nsx"
	post '/make_current_vrni/:id', to: 'admin_files/vrni_applications#current', as: "make_current_vrni_ipaddr" 
	post '/make_current_nsx/:id', to: 'protocol_files/nsx_managers#current', as: "make_current_nsx_ipaddr" 

#   Sessions
	get '/signup' => 'user_files/users#new'
	post '/login' => 'sessions#create'
	get '/login', to: 'sessions#new'
	get '/logout' => 'sessions#destroy'
	post '/user' => 'user_files/users#create'
	get '/home', to: 'user_files/users#home', as: "home"
	get '/ui', to: 'user_files/users#admin_home', as: "admin_home"
	get '/login_button', to: 'user_files/users#login_button', as: "login_button"
	get '/signup_button', to: 'user_files/users#signup_button', as: "signup_button"

#   Users
	get '/user/:id/notify', to: 'user_files/users#notification_email', as: 'notification_email'
	get '/email', to: "user_files/users#remind_each_user", as: "remind_each_user"
	post '/import_users', to: "user_files/users#import_users", as: "import_users"
	post '/create_user', to: "user_files/users#manual_new_user", as: "manual_new_user"
	get '/delete_user/:id', to: 'user_files/users#delete_user', as: "delete_user"
	get '/search_groups', to: 'user_files/users#search_security_groups', as: "search_security_groups"
	post '/new_user', to: 'user_files/users#create', as: "create_a_user"
	get '/add_sec_to_user/:task_id/user/:user_id', to: 'security_files/sec_groups#add_sec_to_user', as: "add_sec_to_user"
	patch '/user_update/:id', to: 'user_files/users#update', as: "update_a_user"

#   Suggested Rules
	post "/sug_save", to: "fire_wall_files/sug_rules#edit_sug_save", as: "edit_sug_save"
	post "/sug_cancel", to: "fire_wall_files/sug_rules#edit_sug_cancel", as: "edit_sug_cancel"

	patch "/add_sug_rules/:id", to: "fire_wall_files/sug_rules#add_sug_rules", as: "add_sug_rules" # change the value of suggested rule submit_sug tag
	get "/add_sug_rules/:id", to: "fire_wall_files/sug_rules#add_sug_rules", as: "add_sug_rules_get" # change the value of suggested rule submit_sug tag
	get "/create_fw_rules", to: "fire_wall_files/sug_rules#create_fw_rules", as: "create_fw_rules"
	get '/delete_item/:rule_id/:type/:type_id/:which_controller', to: "fire_wall_files/sug_rules#delete_sug_item", as: "delete_sug_item"
	post '/create_sug_rule', to: 'fire_wall_files/sug_rules#add_new_sug_rule', as: 'add_new_sug_rule'

#   Apps - DISREGARD: apps have been made redundant and so removed from front end 
	get "/app/:id/get_app_fw_rules", to: "app#get_app_fw_rules", as: "get_app_fw_rules" # get route for imported app rules
	get "/create_app_sec_gp_and_fw_rules", to: "app#create_app_sec_gp_and_fw_rules", as: "sec_gp_and_fw_rules"

#   Email

app/views/layouts/new_rule_partials/_action_options.html.erb
<% if @which_controller == "sec_group" %>
	<span class="flex_column">
		<span class="action_item_cell flex_column">
			<%= link_to add_to_table_column_path("action", "allow", 0, @rule.id, @which_controller, 0), :method => :post, :remote => true do %>
				<button>Allow</button>
			<% end %>
			<%= link_to add_to_table_column_path("action", "block", 0, @rule.id, @which_controller, 0), :method => :post, :remote => true do %>
				<button>Block</button>
			<% end %>
			<%= link_to add_to_table_column_path("action","reject", 0, @rule.id, @which_controller, 0), :method => :post, :remote => true do %>
				<button>Reject</button>
			<% end %>
		</span>
	</span>
<% else %>
	<span class="flex_column">
		<span class="action_item_cell flex_column">
			<%= link_to add_to_table_column_path("action", "allow", @template.id, @rule.id, @which_controller, 0), :method => :post, :remote => true do %>
				<button>Allow</button>
			<% end %>
			<%= link_to add_to_table_column_path("action", "block", @template.id, @rule.id, @which_controller, 0), :method => :post, :remote => true do %>
				<button>Block</button>
			<% end %>
			<%= link_to add_to_table_column_path("action","reject", @template.id, @rule.id, @which_controller, 0), :method => :post, :remote => true do %>
				<button>Reject</button>
			<% end %>
		</span>
	</span>
<% end %>

app/views/layouts/new_rule_partials/_name_option.html.erb
<% if @which_controller == "sec_group" %>
	<%= form_tag(add_protocol_by_num_to_table_path, :class => "", remote: true, :method => "get") do %>
	    <div class="flex_row">
		    <%= text_field_tag :text_input, params[:text_input], :class => "body_font", :class => "edit_sug_search_textbox", placeholder: "Custom rule name" %>
			<%= hidden_field_tag :which_controller, @which_controller %>
			<%= hidden_field_tag :type, "name" %>
			<%= hidden_field_tag :template_id, 0 %>
			<%= hidden_field_tag :rule_id, @rule.id %>
		    <%= button_tag :class => "template_name_btn shadow_no_hover", :name => nil do %>
			    <i class="fa fa-save"></i>
		    <% end %>
	    </div>
	<% end %>
<% else %>
	<%= form_tag(add_protocol_by_num_to_table_path, :class => "", remote: true, :method => "get") do %>
	    <div class="flex_row">
		    <%= text_field_tag :text_input, params[:text_input], :class => "body_font", :class => "edit_sug_search_textbox", placeholder: "Custom rule name" %>
			<%= hidden_field_tag :which_controller, @which_controller %>
			<%= hidden_field_tag :type, "name" %>
			<%= hidden_field_tag :template_id, @template.id %>
			<%= hidden_field_tag :rule_id, @rule.id %>
		    <%= button_tag :class => "template_name_btn shadow_no_hover", :name => nil do %>
			    <i class="fa fa-save"></i>
		    <% end %>
	    </div>
	<% end %>
<% end %>

app/views/layouts/new_rule_partials/_port_options.html.erb
<% if @which_controller == "rule_template" %>
	<div class="add_port_ranges">
		<%= form_tag add_to_ports_column_path, :class => "", remote: true, :method => "get" do %>
			<%= hidden_field_tag :which_controller, @which_controller %>
			<%= hidden_field_tag :template_id, @template.id %>
			<%= hidden_field_tag :rule_id, @rule.id %>
			<span class="flex_column">
			    <%= text_field_tag :source, params[:source], :class => "edit_sug_search_textbox", placeholder: "Source Port" %>
				<%= text_field_tag :destination, params[:destination], :class => "edit_sug_search_textbox", placeholder: "Destination Port" %>
			</span>
			<span class="flex_row justify-content-start">
				<span class="btn title_font">Set</span>
			    <%= button_tag "Submit", :class => "edit_sug_search_btn", :name => nil do %>
				    <i class="fa fa-check"></i>
			    <% end %>
		    </span>
		<% end %>
	</div>
	<div class="other_service">
		<%= form_tag(search_vmware_sys_objs_path, remote: true, :method => "get", id: "service_search_form") do %>
	    	<%= hidden_field_tag :which_controller, @which_controller %>
	    	<%= hidden_field_tag :template_id, @template_id %>
			<%= hidden_field_tag :which_column, "service" %>
			<%= hidden_field_tag :rule_id, @rule.id %>
		    <%= text_field_tag :text_input, params[:text_input], :class => "edit_sug_search_textbox", placeholder: "Search for Applications" %>
			<span class="flex_row submit_section justify-content-start">
				<span class="btn title_font">Search</span>
			    <%= button_tag "Search", :class => "edit_sug_search_btn", :name => nil do %>
				    <i class="fa fa-check"></i>
			    <% end %>
			</span>
		<% end %>
	</div>
<% else %>
	<div class="add_port_ranges">
		<%= form_tag add_to_ports_column_path, :class => "", remote: true, :method => "get" do %>
			<%= hidden_field_tag :which_controller, @which_controller %>
			<%= hidden_field_tag :template_id, 0 %>
			<%= hidden_field_tag :rule_id, @rule.id %>
			<span class="flex_column">
			    <%= text_field_tag :source, params[:source], :class => "edit_sug_search_textbox", placeholder: "Source Port" %>
				<%= text_field_tag :destination, params[:destination], :class => "edit_sug_search_textbox", placeholder: "Destination Port" %>
			</span>
			<span class="flex_row justify-content-start">
				<span class="btn title_font">Set</span>
			    <%= button_tag "Submit", :class => "edit_sug_search_btn", :name => nil do %>
				    <i class="fa fa-check"></i>
			    <% end %>
		    </span>
		<% end %>
	</div>

	<div class="other_service">
		<%= form_tag(search_vmware_sys_objs_path, remote: true, :method => "get", id: "service_search_form") do %>
	    	<%= hidden_field_tag :which_controller, @which_controller %>
	    	<%= hidden_field_tag :template_id, 0 %>
			<%= hidden_field_tag :which_column, "service" %>
			<%= hidden_field_tag :rule_id, @rule.id %>
		    <%= text_field_tag :text_input, params[:text_input], :class => "edit_sug_search_textbox", placeholder: "Search for Applications" %>

			<span class="flex_row submit_section justify-content-start">
				<span class="btn title_font">Search</span>
			    <%= button_tag "Search", :class => "edit_sug_search_btn", :name => nil do %>
			    <i class="fa fa-check"></i>
			</span>
		    <% end %>
		<% end %>
	</div>
<% end %>

app/views/layouts/new_rule_partials/_protocol_options.html.erb
<% if @which_controller == "rule_template" %>
	<span class="flex_column">

		<div class="dropdown">
		  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		    Select
		  </button>
		  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
		    <a class="dropdown-item" href="#"><%= button_to "HTTPS", add_to_table_column_path("protocol", "https", @template.id, @rule.id, @which_controller, 0), :class => "edit_sug_system_obj_search_cell", :method => :post, :remote => true %></a>
		    <a class="dropdown-item" href="#"><%= button_to "HTTP", add_to_table_column_path("protocol", "http", @template.id, @rule.id, @which_controller, 0), :class => "edit_sug_system_obj_search_cell", :method => :post, :remote => true %></a>
		    <a class="dropdown-item" href="#"><%= button_to "UDP", add_to_table_column_path("protocol", "udp", @template.id, @rule.id, @which_controller, 0), :class => "edit_sug_system_obj_search_cell", :method => :post, :remote => true %></a>
		    <a class="dropdown-item" href="#"><%= button_to "TCP", add_to_table_column_path("protocol", "tcp", @template.id, @rule.id, @which_controller, 0), :class => "edit_sug_system_obj_search_cell", :method => :post, :remote => true %></a>
		    <a class="dropdown-item" href="#">
		    	<%= form_tag(add_protocol_by_num_to_table_path, :class => "", remote: true, :method => "get") do %>
				    <div class="flex_row">
					    <%= text_field_tag :text_input, params[:text_input], :class => "edit_sug_search_textbox", placeholder: "Protocol Number" %>
					    <%= hidden_field_tag("page_name", "1", :id => "page_no") %>
						<%= hidden_field_tag :param_name, 'param_value', {:id => 'ashish_id', :name => 'Other: insert the protocol number'}%>
						<%= hidden_field_tag :which_controller, @which_controller %>
						<%= hidden_field_tag :which_action, "manual" %>
						<%= hidden_field_tag :template_id, @template.id %>
						<%= hidden_field_tag :rule_id, @rule.id %>
					    <%= button_tag "Insert", :class => "body_font", :name => nil do %>
					    <i class="fa fa-search"></i>
				    <% end %>
				    </div>
				<% end %>
			</a>
		  </div>
		</div>
	</span>
<% else %>
	<span class="flex_column">
		<div class="dropdown">
		  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		    Select
		  </button>
		  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
		    <a class="dropdown-item" href="#"><%= button_to "HTTPS", add_to_table_column_path("protocol", "https", 0, @rule.id, @which_controller, 0), :class => "edit_sug_system_obj_search_cell", :method => :post, :remote => true %></a>
		    <a class="dropdown-item" href="#"><%= button_to "HTTP", add_to_table_column_path("protocol", "http", 0, @rule.id, @which_controller, 0), :class => "edit_sug_system_obj_search_cell", :method => :post, :remote => true %></a>
		    <a class="dropdown-item" href="#"><%= button_to "UDP", add_to_table_column_path("protocol", "udp", 0, @rule.id, @which_controller, 0), :class => "edit_sug_system_obj_search_cell", :method => :post, :remote => true %></a>
		    <a class="dropdown-item" href="#"><%= button_to "TCP", add_to_table_column_path("protocol", "tcp", 0, @rule.id, @which_controller, 0), :class => "edit_sug_system_obj_search_cell", :method => :post, :remote => true %></a>
		    <a class="dropdown-item" href="#">
		    	<%= form_tag(add_protocol_by_num_to_table_path, :class => "", remote: true, :method => "get") do %>
				    <div class="flex_row">
					    <%= text_field_tag :text_input, params[:text_input], :class => "edit_sug_search_textbox", placeholder: "Protocol Number" %>
					    <%= hidden_field_tag("page_name", "1", :id => "page_no") %>
						<%= hidden_field_tag :param_name, 'param_value', {:id => 'ashish_id', :name => 'Other: insert the protocol number'}%>
						<%= hidden_field_tag :which_controller, @which_controller %>
						<%= hidden_field_tag :which_action, "manual" %>
						<%= hidden_field_tag :template_id, 0 %>
						<%= hidden_field_tag :rule_id, @rule.id %>
					    <%= button_tag "Insert", :class => "body_font", :name => nil do %>
					    <i class="fa fa-search"></i>
				    <% end %>
				    </div>
				<% end %>
			</a>
		  </div>
		</div>
	</span>

<% end %>

app/views/layouts/new_rule_partials/_search_vmware_sys_objs.html.erb
<% if @which_controller == "rule_template" %>
	<% if !@sys_objs.nil? %>
		<% @sys_objs.each do |sys_obj| %>
			<span class="flex_column edit_sug_system_obj_search_cell shadow">
				<% if @which_column == "source" %>
					<%= link_to add_to_table_column_path("source", "vmware_system_object", @template_id, @rule.id, @which_controller, sys_obj.id), :method => :post, :remote => true do %>
						<p class="body_font"><%= sys_obj.vm_name %></p>
					<% end %>
				<% elsif @which_column == "destination" %>
					<%= link_to add_to_table_column_path("destination", "vmware_system_object", @template_id, @rule.id, @which_controller, sys_obj.id), :method => :post, :remote => true do %>
						<p class="body_font"><%= sys_obj.vm_name %></p>
					<% end %>
				<% elsif @which_column == "service" %>
					<%= link_to add_to_service_table_path(@template_id, sys_obj.id, @rule.id, @which_controller), :remote => true do %>
						<p class="body_font"><%= sys_obj.vm_name %></p>
					<% end %>
				<% end %>
			</span>
		<% end %>
	<% end %>
<% elsif @which_controller == "sec_group" %>
	<% if !@sys_objs.nil? %>
		<% @sys_objs.each do |sys_obj| %>
			<span class="flex_column edit_sug_system_obj_search_cell shadow">
				<% if @which_column == "source" %>
					<%= link_to add_to_table_column_path("source", "vmware_system_object", 0, @rule.id, @which_controller, sys_obj.id), :method => :post, :remote => true do %>
						<p class="body_font"><%= sys_obj.vm_name %></p>
					<% end %>
				<% elsif @which_column == "destination" %>
					<%= link_to add_to_table_column_path("destination", "vmware_system_object", 0, @rule.id, @which_controller, sys_obj.id), :method => :post, :remote => true do %>
						<p class="body_font"><%= sys_obj.vm_name %></p>
					<% end %>
				<% elsif @which_column == "service" %>
					<%= link_to add_to_service_table_path(0, sys_obj.id, @rule.id, @which_controller), :remote => true do %>
						<p class="body_font"><%= sys_obj.vm_name %></p>
					<% end %>
				<% end %>
			</span>
		<% end %>
	<% end %>
<% end %>

app/views/layouts/new_rule_partials/_source_dest_options.html.erb
<% if @which_controller == "rule_template" %>
	<div class="edit_sug_searchbar">
		<%= form_tag(search_vmware_sys_objs_path, remote: true, :method => "get", id: "search-form") do %>
			<span class="flex_row">
			    <%= text_field_tag :text_input, params[:text_input], :class => "edit_sug_search_textbox", placeholder: "System Objects" %>
		    	<%= hidden_field_tag :which_controller, @which_controller %>
		    	<%= hidden_field_tag :template_id, @template.id %>
				<%= hidden_field_tag :which_column, @type %>
				<%= hidden_field_tag :rule_id, @rule.id %>
			    <%= button_tag :class => "edit_sug_search_btn shadow_no_hover", :name => nil do %>
				    <i class="fa fa-search white_text"></i>
			    <% end %>
			</span>
		<% end %>
	</div>
<% elsif @which_controller == "sec_group" %>	
	<div class="edit_sug_searchbar">
		<%= form_tag(search_vmware_sys_objs_path, remote: true, :method => "get", id: "search-form") do %>
			<span class="flex_row">
			    <%= text_field_tag :text_input, params[:text_input], :class => "edit_sug_search_textbox", placeholder: "System Objects" %>
		    	<%= hidden_field_tag :which_controller, @which_controller %>
		    	<%= hidden_field_tag :template_id, 0 %>
				<%= hidden_field_tag :which_column, @type %>
				<%= hidden_field_tag :rule_id, @rule.id %>
			    <%= button_tag :class => "edit_sug_search_btn shadow_no_hover", :name => nil do %>
				    <i class="fa fa-search blue_text"></i>
			    <% end %>
			</span>
		<% end %>
	</div>
<% end %>