config/routes.rb
Rails.application.routes.draw do


	resources :user_groups

	namespace :security_files do
		resources :sec_tags
		resources :sec_group_templates
		resources :flows
	end

	namespace :protocol_files do
		resources :nsx_managers
	end

	namespace :admin_files do
		resources :settings
		resources :vrni_applications
	end

	namespace :user_files do
	  resources :users
	end

	namespace :fire_wall_files do
		resources :temp_fire_rules
		resources :rule_histories
		resources :rule_templates
		resources :fire_rules
		resources :sug_rule
	end

	namespace :security_files do
		resources :sec_groups
	end
	
	resources :services
	resources :applied_tos
	resources :nested_sec_gps
	resources :app_objs
	resources :vms

	root 'user_files/users#home'

	resources :app do

		namespace :fire_wall_files do
			resources :temp_fire_rules do
				resources :port_ranges
				resources :protocols
				resources :applied_tos
				resources :destinations
				resources :sources
				resources :services
			end
		end

		collection { post :import } # import function's routes for the app csv file
	    resources :tiers do

	    	namespace :fire_wall_files do
		    	resources :sug_rules do
		    		resources :port_ranges
		    		resources :protocols
		    		resources :applied_tos
		    		resources :destinations
		    		resources :sources
		    		resources :services
		    	end
		    end

	    	resources :app_objs do
	    		namespace :fire_wall_files do
			  		resources :fire_rules do
						resources :port_ranges
						resources :protocols
						resources :applied_tos
						resources :destinations
						resources :sources
						resources :services
					end
				end
			end
		end
	end

	resources :sec_groups do
		collection {post :import_groups_and_objs} # import function's routes for the app csv file

		namespace :fire_wall_files do
			resources :sug_rules do
				collection { patch :add_sug_rules }
				resources :port_ranges
				resources :protocols
				resources :applied_tos
				resources :destinations
				resources :sources
				resources :services
			end
		end
		
		resources :nested_sec_gps do
			resources :app_objs
		end		
	end

	namespace :fire_wall_files do
		resources :fire_rules do
			collection { get :import_fw_rules }
			resources :port_ranges
			resources :protocols
			resources :applied_tos
			resources :destinations
			resources :sources
			resources :services
		end
	end
	
	namespace :fire_wall_files do
		resources :temp_fire_rules do

			resources :port_ranges
			resources :protocols
			resources :applied_tos
			resources :destinations
			resources :sources
			resources :services

		end
	end

	resources :sec_groups do
		namespace :fire_wall_files do
			resources :temp_fire_rules do

				resources :port_ranges
				resources :protocols
				resources :applied_tos
				resources :destinations
				resources :sources
				resources :services

			end
		end
	end


	resources :sec_groups do
		resources :flows
	end

	resources :nested_sec_gps do
		resources :flows
	end


###########################
#   Custom Routes Below
###########################


#   Flows 
	get '/allow_flow/:id', to: 'security_files/flows#allow_flow', as: "allow_flow"
	get '/deny_flow/:id', to: 'security_files/flows#deny_flow', as: "deny_flow"
	delete '/remove_flow/:id', to: 'security_files/flows#remove_flow_from_nsx', as: "remove_flow_from_nsx"

#   Application
	post '/filter/:column_array/object/:object_class', to: 'application#filter_columns', as: "filter_columns"
	get '/columns/select', to: 'application#select_filter_columns', as: "select_filter_columns"
	get '/filter/:row_totals/columns/:column_array/:origin', to: 'application#add_column_sort_modal_item', as: "add_column_sort_modal_item"

# 	Histories
	get '/remove_rule/:rule_id', to: "fire_wall_files/rule_histories#remove_nsx_rule", as: "remove_nsx_rule"
	get '/resubmit_rule/:rule_id', to: "fire_wall_files/rule_histories#resubmit_nsx_rule", as: "resubmit_nsx_rule"

#   rule_table
	get '/change_name', to: "application#add_to_table_column"

#   Rule Creation
	get '/sysobj/:template_id', to: "application#add_to_table_column", as: "add_protocol_by_num_to_table"
	get '/sgp_task/:task_id/:user_id', to: 'user_files/users#attach_sec_group_user', as: "attach_sec_group_user"
	get '/new_template_rule/:template_id/:rule_id', to: 'fire_wall_files/rule_templates#add_rules_to_template', as: "add_rules_to_template"
	post '/new_rule/:type/:which_action/:template_id/:rule_id/:which_controller/:vmware_object_id', to: 'application#add_to_table_column', as: "add_to_table_column"
	get '/delete_item/:template_id/:rule_id/:item_type/:item_id/:which_controller', to: "application#delete_rule_item", as: "delete_template_rule_item"

#   Templates
    post '/template/:id/name', to: 'fire_wall_files/rule_templates#set_template_name', as: "set_template_name"
	get '/new_template/', to: 'fire_wall_files/rule_templates#create_a_template', as: "create_a_template"
	get '/template/:id/new_rule/:rule_id', to: 'fire_wall_files/rule_templates#cancel_rule_to_template', as: "cancel_rule_to_template"
	get '/template/:id/rules', to: 'fire_wall_files/rule_templates#see_template_rules', as: "see_template_rules_lite"
	get '/template/:id/rules/:rule', to: 'fire_wall_files/rule_templates#see_template_rules', as: "see_template_rules"
	get '/template/:id', to: 'fire_wall_files/rule_templates#edit_template', as: "edit_template"
	delete '/template/:id', to: 'fire_wall_files/rule_templates#destroy', as: "delete_a_template"
	delete 'template/:template_id/rule/:rule_id', to: 'fire_wall_files/rule_templates#delete_a_template_rule', as: "delete_a_template_rule"
	get 'template/:template_id/rule/:rule_id', to: 'fire_wall_files/rule_templates#edit_a_template_rule', as: "edit_a_template_rule"
	# get 'search_templates', to: "fire_wall_files/rule_templates#search_templates"
	post 'template/:template_id', to: "fire_wall_files/rule_templates#add_template_to_group", as: "add_template_to_group"
	get '/search_templates', to: "fire_wall_files/rule_templates#search_templates", as: "search_templates"
	delete '/remove_template/:template_id', to: "fire_wall_files/rule_templates#remove_template_from_group", as: "remove_template_from_group"

#   User Setting
	get '/settings', to: 'admin_files/settings#index', as: "settings_index"
	patch '/edit_manager/:nsx', to: 'admin_files/settings#update_nsx', as: "nsx_manager_edit"
	patch '/edit_manager/:vrni', to: 'admin_files/settings#update_vrni', as: "vrin_machine_edit"
	post '/settings_error', to: 'admin_files/settings#settings_error', as: "settings_error"
	post '/settings_save', to: 'admin_files/settings#settings_save', as: "settings_save"
	post '/settings_cancel', to: 'admin_files/settings#settings_cancel', as: "settings_cancel"
	patch '/settings_update/:id/:type', to: 'admin_files/settings#settings_update', as: "settings_update"

#   Children of Settings Class
	post '/vrni_applications', to: 'admin_files/vrni_applications#create', as: "add_vrni"
	post '/nsx_managers', to: 'protocol_files/nsx_managers#create', as: "add_nsx"
	put '/edit_vrni/:id', to: 'admin_files/vrni_applications#destroy', as: "edit_vrni"
	put '/edit_nsx/:id', to: 'protocol_files/nsx_managers#destroy', as: "edit_nsx"
	delete '/delete_vrni/:id', to: 'admin_files/vrni_applications#destroy', as: "delete_vrni"
	delete '/delete_nsx/:id', to: 'protocol_files/nsx_managers#destroy', as: "delete_nsx"
	post '/make_current_vrni/:id', to: 'admin_files/vrni_applications#current', as: "make_current_vrni_ipaddr" 
	post '/make_current_nsx/:id', to: 'protocol_files/nsx_managers#current', as: "make_current_nsx_ipaddr" 

#   Sessions
	get '/signup' => 'user_files/users#new'
	post '/login' => 'sessions#create'
	get '/login', to: 'sessions#new'
	get '/logout' => 'sessions#destroy'
	post '/user' => 'user_files/users#create'
	get '/home', to: 'user_files/users#home', as: "home"
	get '/ui', to: 'user_files/users#admin_home', as: "admin_home"
	get '/login_button', to: 'user_files/users#login_button', as: "login_button"
	get '/signup_button', to: 'user_files/users#signup_button', as: "signup_button"

#   Users
	get '/user/:id/notify', to: 'user_files/users#notification_email', as: 'notification_email'
	get '/email', to: "user_files/users#remind_each_user", as: "remind_each_user"
	post '/import_users', to: "user_files/users#import_users", as: "import_users"
	post '/create_user', to: "user_files/users#manual_new_user", as: "manual_new_user"
	get '/delete_user/:id', to: 'user_files/users#delete_user', as: "delete_user"
	get '/search_groups', to: 'user_files/users#search_security_groups', as: "search_security_groups"
	post '/new_user', to: 'user_files/users#create', as: "create_a_user"
	get '/add_sec_to_user/:task_id/user/:user_id', to: 'security_files/sec_groups#add_sec_to_user', as: "add_sec_to_user"
	patch '/user_update/:id', to: 'user_files/users#update', as: "update_a_user"

#   Suggested Rules
	post "/sug_save", to: "fire_wall_files/sug_rules#edit_sug_save", as: "edit_sug_save"
	post "/sug_cancel", to: "fire_wall_files/sug_rules#edit_sug_cancel", as: "edit_sug_cancel"

	patch "/add_sug_rules/:id", to: "fire_wall_files/sug_rules#add_sug_rules", as: "add_sug_rules" # change the value of suggested rule submit_sug tag
	get "/add_sug_rules/:id", to: "fire_wall_files/sug_rules#add_sug_rules", as: "add_sug_rules_get" # change the value of suggested rule submit_sug tag
	get "/create_fw_rules", to: "fire_wall_files/sug_rules#create_fw_rules", as: "create_fw_rules"
	get '/delete_item/:rule_id/:type/:type_id/:which_controller', to: "fire_wall_files/sug_rules#delete_sug_item", as: "delete_sug_item"
	post '/create_sug_rule', to: 'fire_wall_files/sug_rules#add_new_sug_rule', as: 'add_new_sug_rule'

#   Apps - DISREGARD: apps have been made redundant and so removed from front end 
	get "/app/:id/get_app_fw_rules", to: "app#get_app_fw_rules", as: "get_app_fw_rules" # get route for imported app rules
	get "/create_app_sec_gp_and_fw_rules", to: "app#create_app_sec_gp_and_fw_rules", as: "sec_gp_and_fw_rules"

#   Email

app/models/rule_template.rb
class RuleTemplate < ApplicationRecord
	has_many :fire_rules

	has_many :sec_group_templates
	has_many :sec_groups, through: :sec_group_templates

	def self.search(input)
		if input == ""
			return RuleTemplate.all
		else
			test_against = "%#{input}%"
			return RuleTemplate.where("name LIKE ?", test_against)
		end
	end

end

app/controllers/fire_wall_files/fire_rule_controller.rb
class FireRuleController < ApplicationController
  before_action :set_fire_rule, only: [:show, :edit, :update, :destroy]

  def index
    @fire_rules = FireRule.all
  end

  def create
    @fire_rule = FireRule.new(fire_rule_params)

    respond_to do |format|
      if @fire_rule.save
        format.html { redirect_to @fire_rule, notice: 'Fire rule was successfully created.' }
        format.json { render :show, status: :created, location: @fire_rule }
      else
        format.html { render :new }
        format.json { render json: @fire_rule.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @fire_rule.update(fire_rule_params)
        format.html { redirect_to @fire_rule, notice: 'Fire rule was successfully updated.' }
        format.json { render :show, status: :ok, location: @fire_rule }
      else
        format.html { render :edit }
        format.json { render json: @fire_rule.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @fire_rule.destroy
    respond_to do |format|
      format.html { redirect_to fire_rules_url, notice: 'Fire rule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_fire_rule
      @fire_rule = FireRule.find(params[:id])
    end

    def fire_rule_params
      params.fetch(:fire_rule, {})
    end
end

app/controllers/fire_wall_files/rule_histories_controller.rb
module FireWallFiles
  class RuleHistoriesController < ApplicationController
    before_action :set_rule_history, only: [:show, :edit, :update, :destroy]

    def index
      @rule_histories = RuleHistory.all
    end

    def show
    end

    def new
      @rule_history = RuleHistory.new
    end

    def edit
    end

    def remove_nsx_rule
      history_item = RuleHistory.find_by_id(params[:rule_id])

      RuleHistory.remove_nsx_rule(current_user, history_item)

      @rule_histories = RuleHistory.all
      @type = "update_histories"
      respond_to() do |format|
        format.js { render :action => "/user_files/users/admin_dashboard_js_erb/admin_dashboard.js.erb"}
      end
    end

    def resubmit_nsx_rule
      RuleHistory.resubmit_nsx_rule(params[:rule_id], current_user)
      
      @rule_histories = RuleHistory.all
      @type = "update_histories"
      respond_to() do |format|
        format.js { render :action => "/user_files/users/admin_dashboard_js_erb/admin_dashboard.js.erb"}
      end
    end

    def create
      @rule_history = RuleHistory.new(rule_history_params)

      respond_to do |format|
        if @rule_history.save
          format.html { redirect_to @rule_history, notice: 'Rule history was successfully created.' }
          format.json { render :show, status: :created, location: @rule_history }
        else
          format.html { render :new }
          format.json { render json: @rule_history.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @rule_history.update(rule_history_params)
          format.html { redirect_to @rule_history, notice: 'Rule history was successfully updated.' }
          format.json { render :show, status: :ok, location: @rule_history }
        else
          format.html { render :edit }
          format.json { render json: @rule_history.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @rule_history.destroy
      respond_to do |format|
        format.html { redirect_to rule_histories_url, notice: 'Rule history was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_rule_history
        @rule_history = RuleHistory.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def rule_history_params
        params.require(:rule_history).permit(:name, :action, :direction, :pack_type, :user_id)
      end
  end
end

app/controllers/fire_wall_files/temp_fire_rules_controller.rb
module FireWallRules
  class TempFireRulesController < ApplicationController
    before_action :set_temp_fire_rule, only: [:show, :edit, :update, :destroy]

    # GET /temp_fire_rules
    # GET /temp_fire_rules.json
    def index
      @temp_fire_rules = TempFireRule.all
    end

    # GET /temp_fire_rules/1
    # GET /temp_fire_rules/1.json
    def show
    end

    # GET /temp_fire_rules/new
    def new
      @temp_fire_rule = TempFireRule.new
    end

    # GET /temp_fire_rules/1/edit
    def edit
    end

    # POST /temp_fire_rules
    # POST /temp_fire_rules.json
    def create
      @temp_fire_rule = TempFireRule.new(temp_fire_rule_params)

      respond_to do |format|
        if @temp_fire_rule.save
          format.html { redirect_to @temp_fire_rule, notice: 'Temp fire rule was successfully created.' }
          format.json { render :show, status: :created, location: @temp_fire_rule }
        else
          format.html { render :new }
          format.json { render json: @temp_fire_rule.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /temp_fire_rules/1
    # PATCH/PUT /temp_fire_rules/1.json
    def update
      respond_to do |format|
        if @temp_fire_rule.update(temp_fire_rule_params)
          format.html { redirect_to @temp_fire_rule, notice: 'Temp fire rule was successfully updated.' }
          format.json { render :show, status: :ok, location: @temp_fire_rule }
        else
          format.html { render :edit }
          format.json { render json: @temp_fire_rule.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /temp_fire_rules/1
    # DELETE /temp_fire_rules/1.json
    def destroy
      @temp_fire_rule.destroy
      respond_to do |format|
        format.html { redirect_to temp_fire_rules_url, notice: 'Temp fire rule was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_temp_fire_rule
        @temp_fire_rule = TempFireRule.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def temp_fire_rule_params
        params.fetch(:temp_fire_rule, {})
      end
  end
end

app/helpers/rule_templates_helper.rb
module RuleTemplatesHelper
end

app/views/fire_wall_files/rule_templates/_all_templates.html.erb
<span class="flex_column overflow_child">
    <% @templates.each do |rule_template| %>
      <span class="template_rule_container flex_row shadow">
        <span class="rule_name">
            <p class="title_font white_text"><%= rule_template.name %></p>
        </span>
        <span class="rule_actions flex_row">
            <span class="flex_center"><%= link_to edit_template_path(rule_template), remote: true do %>
                    <i class="fa fa-edit small_button blue_text"></i>
                <% end %>
            </span>
            <span class="flex_center"><%= link_to delete_a_template_path(rule_template.id), :method => "delete", remote: true, data: { confirm: 'Are you sure?' } do %>
                    <i class="fa fa-close small_button red_text"></i>
                <% end %>
            </span>   
        </span>
      </span>
    <% end %>

</span>

app/views/fire_wall_files/rule_templates/_all_templates_table.html.erb
<span class="flex_column">
	<% templates.uniq.each do |template| %>
		<div class="dropdown">
			<span class="flex_row">
				<button class="flex_row sg_template_table_title_dropdown_container shadow" type="button" id="id_<%= template.id %>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					<p class="sg_template_table_title_dropdown title_font">
						<%= template.name %> 
					</p>
				</button>
				<% if @type != "reload_sec_group_templates_index" %>
						<%= link_to add_template_to_group_path(template.id), :method => "post", remote: true, format: :js do %>
			                <i class="fa fa-plus small_button"></i>
						<% end %>
				<% else %>
						<%= link_to remove_template_from_group_path(template.id), :method => "delete", remote: true, format: :js do %>
			                <i class="fa fa-close small_button"></i>
						<% end %>
				<% end %>
			</span>
			<div class="dropdown-menu relative sg_template_table_item_dropdown" aria-labelledby="id_<%= template.id %>">
				<%= render :partial => "fire_wall_files/rule_templates/added_rules/current_rules_table", :locals => { :@template => template, :@origin_type => "non" } %>
			</div>
		</div>
	<% end %>
</span>

app/views/fire_wall_files/rule_templates/_show.html.erb
<!-- Center and the right sections of the screen -->
<span class="flex_row template_tables_outer_container">
	<span class="flex_column template_center_section">
		<span class="template_information_section flex_row">
			<%= form_tag set_template_name_path(@template.id), :class => "template_name_form", remote: true do %>
				<span class="flex_row">
					<%= text_field_tag :name, params[:name], placeholder: "Name your template", :class => "edit_sug_search_textbox" %>
					<%= button_tag :class => "template_name_btn shadow_no_hover"  do %>
					    <i class="fa fa-save"></i>
				    <% end %>
				</span>
			<% end %>
		</span>

		<span id="current_rules_table" class="shadow_no_hover">
			<!-- All the template's rules live here -->
			<%= render :partial => 'fire_wall_files/rule_templates/added_rules/current_rules_table' %>
		</span>

		<span class="template_rule_table_header">
			<span id="save_template_rule">
				<!-- Save and Cancel buttons update a template rule -->
				<!-- Look for this in the reload_rule_columns.js.erb, it is added here upon the completion of a controller method -->
			</span>
		</span>

		<span class="shadow_no_hover">
			<span class="template_rule_headers_container flex_column">
				<% if !@template.nil? %>
					<!-- Create & Cancel Buttons Live Here -->
					<%= render :partial => 'fire_wall_files/rule_templates/template_headers', :locals => { :template => @template} %>
				<% end %>
			</span>

			<span class="template_table add_template_rule_container template_table_row flex_column template_table_header">
				<span class="add_template_rule_headers flex_row full_width">
					<!-- Table Headers Live here  -->
				</span>

				<span class="add_template_rule_body">
					<!-- Create template rule section lives here -->
					<%= render :partial => 'fire_wall_files/rule_templates/new_rule/add_template_rule_body' %>
				</span>
			</span>
		</span>
	</span>

	<span class="flex_column template_right_section">
		<span>
			<p id="suggestion_column_title" class="edit_sug_table_headers"></p>
			<!-- Title of search lives here -->
		</span>
		<span id="suggestion_column_searchbar" class="">
			<!-- Search forms live here -->
		</span>
		<span class="search_widget_result_container ">

			<span id="remove_on_first_search">
				<p class="edit_sug_table_headers"></p>
			</span>
			<span id="column_tables_container">

			</span>
		</span>
	</span>
</span>

app/views/fire_wall_files/rule_templates/_template_headers.html.erb
<span class="flex_row">
	<span class="template_rule_table_new">
		<!-- <= link_to "new", template_rule_create_path(@template.id), :remote => true %> -->
	</span>
<!-- 	<span>
		<= link_to "all rules", see_template_rules_lite_path(@template.id), :remote => true %>
	</span> -->
</span>

app/views/fire_wall_files/rule_templates/create_rule_table_cells.js.erb
<% case(@type) %>
	<% when "service" %>
		$('#ports_table_partial_area').html("");
		$('#ports_table_partial_area').append("<%= j render :partial => 'layouts/rule_column_templates/edit_table_services_and_ports' %>");
	<% when "destination" %>
		$('#destinations_table_partial_area').html("");
		$('#destinations_table_partial_area').append("<%= j render :partial => 'layouts/rule_column_templates/edit_table_destinations' %>");
	<% when "source" %>
		$('#sources_table_partial_area').html("");
		$('#sources_table_partial_area').append("<%= j render :partial => 'layouts/rule_column_templates/edit_table_sources' %>");
	<% when "action" %>
		$('#action_table_partial_area').html("");
		$('#action_table_partial_area').append("<%= j render :partial => 'layouts/rule_column_templates/edit_table_action' %>");
	<% when "protocol" %>
		$('#protocols_table_partial_area').html("");
		$('#protocols_table_partial_area').append("<%= j render :partial => 'layouts/rule_column_templates/edit_table_protocol' %>");
<% end %>

app/views/fire_wall_files/rule_templates/index.html.erb
<div class="templates_page_container flex_row">
  <span class="templates_side_nav flex_column">
  <!-- This is the button to show all templates -->
      <span class="flex_row shadow">
        <a for="second_collapse_header" class="" data-toggle="collapse" href="#nav_sys_templates" aria-expanded="true" aria-controls="nav_sys_templates"><p class="side_nav_lvl_1_title title_font white_text templates_page_title">All Templates</p></a>
        <%= link_to create_a_template_path, :remote => true do %>
          <%= image_tag "add_highlight_two.png", :class => "new_template_image" %>
        <% end %>
      </span>

      <!-- This is the form providing template search -->
      <div class="searchbar">
        <%= form_tag(search_templates_path, remote: true, :method => "get", id: "search-form") do %>
          <span class="flex_row">
              <%= text_field_tag :text_input, params[:text_input], :class => "edit_sug_search_textbox", placeholder: "Search Templates" %>
              <%= hidden_field_tag :origin, params[:origin], :value => "templates_index" %>
              <%= button_tag "Go", :class => "edit_sug_search_btn", :name => nil do %>
          <i class="fa fa-search"></i>
        <% end %>
          </span>
        <% end %>
      </div>
    <div class=" flex_column fill_height">
      
      <span class="nav_sys_all_templates_area shadow_no_hover dark_background" data-target="#nav_sys_sec_groups_header">

        <!-- This is the list of all templates -->
        <div id="nav_sys_templates" class="overflow_parent templates_side_nav_bottom">
          <%= render :partial => "all_templates", :template => @rule_template %>
        </div>
      </span>
    </div>
  </span>
  <span class="templates_main_body_container flex_column">
    <!-- <= render :partial => 'rule_templates/show' %> -->
  </span>

</div>